export type Language = 'es' | 'en';

export interface Translations {
  // Header
  appTitle: string;
  darkMode: string;
  lightMode: string;

  // Tabs
  tabPart1: string;
  tabPart2: string;
  tabPart1Description: string;
  tabPart2Description: string;

  // Voice Input
  voiceInput: string;
  startListening: string;
  stopListening: string;
  listening: string;
  processing: string;
  unsupported: string;
  voiceNotSupported: string;
  microphoneError: string;

  // Transcription
  transcription: string;
  noTranscriptionYet: string;
  clearTranscription: string;

  // Last Command
  lastCommand: string;
  commandType: string;
  noCommandYet: string;

  // Add Item Form
  addItemManually: string;
  description: string;
  quantity: string;
  unitPrice: string;
  addItem: string;

  // Invoice Items
  invoiceItems: string;
  noItemsYet: string;
  edit: string;
  delete: string;

  // Invoice Details
  invoiceDetails: string;
  invoiceNumber: string;
  autoGenerated: string;
  invoiceDate: string;
  dueDate: string;
  customerName: string;
  customerAddress: string;
  taxRate: string;
  notes: string;

  // Placeholders
  placeholderInvoiceNumber: string;
  placeholderCustomerName: string;
  placeholderCustomerAddress: string;
  placeholderTaxRate: string;
  placeholderNotes: string;

  // Calculations
  subtotal: string;
  tax: string;
  total: string;

  // PDF
  generatePDF: string;
  generating: string;

  // PDF Template
  pdfInvoiceTitle: string;
  pdfBillTo: string;
  pdfQty: string;
  pdfTotalDue: string;
  pdfThankYou: string;
  pdfPaymentInstructions: string;
  pdfCompanyName: string;
  pdfCompanyAddress: string;
  pdfCompanyPhone: string;
  pdfCompanyEmail: string;

  // Voice Commands Help
  voiceCommandsHelp: string;
  commandExamples: string;

  addItemCommand: string;
  addItemCommand2: string;
  addItemCommand3: string;
  customerCommand: string;
  taxCommand: string;

  // Errors
  error: string;
  required: string;
  invalidNumber: string;

  // Landing Page
  landingTitlePrefix: string;
  landingTitleHighlight: string;
  landingSubtitle: string;
  launchApp: string;

  // Features
  featureVoiceTitle: string;
  featureVoiceDesc: string;
  featureExtractionTitle: string;
  featureExtractionDesc: string;
  featurePdfTitle: string;
  featurePdfDesc: string;
  featureMultiLangTitle: string;
  featureMultiLangDesc: string;
}

export const translations: Record<Language, Translations> = {
  es: {
    // Header
    appTitle: 'Facturación por Voz',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',

    // Tabs
    tabPart1: 'Generador de Facturas',
    tabPart2: 'Funciones Avanzadas',
    tabPart1Description: 'Crear facturas con voz',
    tabPart2Description: 'Gestión empresarial de pintura',

    // Voice Input
    voiceInput: 'Entrada de Voz',
    startListening: 'Iniciar Escucha',
    stopListening: 'Detener',
    listening: 'Escuchando...',
    processing: 'Procesando...',
    unsupported: 'No Compatible',
    voiceNotSupported: 'Tu navegador no soporta reconocimiento de voz',
    microphoneError: 'Error con el micrófono. Verifica los permisos.',

    // Transcription
    transcription: 'Transcripción',
    noTranscriptionYet: 'No hay transcripción todavía. Presiona el botón para comenzar.',
    clearTranscription: 'Limpiar',

    // Last Command
    lastCommand: 'Último Comando',
    commandType: 'Tipo de Comando',
    noCommandYet: 'No hay comandos todavía',

    // Add Item Form
    addItemManually: 'Agregar Artículo Manualmente',
    description: 'Descripción',
    quantity: 'Cantidad',
    unitPrice: 'Precio Unitario',
    addItem: 'Agregar',

    // Invoice Items
    invoiceItems: 'Artículos de la Factura',
    noItemsYet: 'No hay artículos todavía. Usa voz o el formulario para agregar.',
    edit: 'Editar',
    delete: 'Eliminar',

    // Invoice Details
    invoiceDetails: 'Detalles de la Factura',
    invoiceNumber: 'N° de Factura',
    autoGenerated: 'Auto',
    invoiceDate: 'Fecha',
    dueDate: 'Vencimiento',
    customerName: 'Cliente',
    customerAddress: 'Dirección',
    taxRate: 'IVA (%)',
    notes: 'Notas',

    // Placeholders
    placeholderInvoiceNumber: '0001',
    placeholderCustomerName: 'Edificio Central S.A.',
    placeholderCustomerAddress: 'Av. Principal 123, Col. Centro, Ciudad, CP 01234',
    placeholderTaxRate: '16',
    placeholderNotes: 'Trabajo de pintura comercial completado. Pago dentro de 30 días.',

    // Calculations
    subtotal: 'Subtotal',
    tax: 'Impuesto',
    total: 'Total',

    // PDF
    generatePDF: 'Generar PDF',
    generating: 'Generando...',

    // PDF Template
    pdfInvoiceTitle: 'FACTURA',
    pdfBillTo: 'Facturar a',
    pdfQty: 'Cant.',
    pdfTotalDue: 'Total a Pagar',
    pdfThankYou: '¡Gracias por su preferencia!',
    pdfPaymentInstructions: 'Por favor realice el pago antes de la fecha de vencimiento. Para consultas, contáctenos a info@empresa.com',
    pdfCompanyName: 'Tu Empresa',
    pdfCompanyAddress: 'Calle Principal 123',
    pdfCompanyPhone: 'Teléfono',
    pdfCompanyEmail: 'Email',

    // Voice Commands Help
    voiceCommandsHelp: 'Ayuda de Comandos de Voz',
    commandExamples: 'Ejemplos de comandos de pintura',
    addItemCommand: 'Añadir 500 pies cuadrados pintura exterior a 3.50',
    addItemCommand2: 'Agregar 10 galones pintura premium a 45',
    addItemCommand3: 'Añadir 8 horas mano de obra a 65',
    customerCommand: 'Cliente es Edificio Torre Central',
    taxCommand: 'IVA 16',

    // Errors
    error: 'Error',
    required: 'Requerido',
    invalidNumber: 'Número inválido',

    // Landing Page
    landingTitlePrefix: 'Facturación',
    landingTitleHighlight: 'por Voz',
    landingSubtitle: 'Crea facturas profesionales solo con tu voz. El futuro de la facturación está aquí.',
    launchApp: 'Iniciar App',

    // Features
    featureVoiceTitle: 'Control por Voz',
    featureVoiceDesc: 'Habla naturalmente para crear facturas al instante.',
    featureExtractionTitle: 'Extracción Inteligente',
    featureExtractionDesc: 'IA detecta automáticamente artículos, precios y fechas.',
    featurePdfTitle: 'PDF Instantáneo',
    featurePdfDesc: 'Genera PDFs profesionales con un solo comando.',
    featureMultiLangTitle: 'Multi-Idioma',
    featureMultiLangDesc: 'Soporte para Inglés y Español incluido.',
  },

  en: {
    // Header
    appTitle: 'Voice Invoicing',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',

    // Tabs
    tabPart1: 'Invoice Generator',
    tabPart2: 'Advanced Features',
    tabPart1Description: 'Create invoices with voice',
    tabPart2Description: 'Painting business management',

    // Voice Input
    voiceInput: 'Voice Input',
    startListening: 'Start Listening',
    stopListening: 'Stop',
    listening: 'Listening...',
    processing: 'Processing...',
    unsupported: 'Unsupported',
    voiceNotSupported: 'Your browser does not support voice recognition',
    microphoneError: 'Microphone error. Check permissions.',

    // Transcription
    transcription: 'Transcription',
    noTranscriptionYet: 'No transcription yet. Press the button to start.',
    clearTranscription: 'Clear',

    // Last Command
    lastCommand: 'Last Command',
    commandType: 'Command Type',
    noCommandYet: 'No commands yet',

    // Add Item Form
    addItemManually: 'Add Item Manually',
    description: 'Description',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    addItem: 'Add',

    // Invoice Items
    invoiceItems: 'Invoice Items',
    noItemsYet: 'No items yet. Use voice or the form to add.',
    edit: 'Edit',
    delete: 'Delete',

    // Invoice Details
    invoiceDetails: 'Invoice Details',
    invoiceNumber: 'Invoice #',
    autoGenerated: 'Auto',
    invoiceDate: 'Date',
    dueDate: 'Due Date',
    customerName: 'Customer',
    customerAddress: 'Address',
    taxRate: 'Tax Rate (%)',
    notes: 'Notes',

    // Placeholders
    placeholderInvoiceNumber: '0001',
    placeholderCustomerName: 'Commercial Building Corp.',
    placeholderCustomerAddress: '123 Business Plaza, Suite 400, City, ST 12345',
    placeholderTaxRate: '10',
    placeholderNotes: 'Commercial painting work completed. Payment due within 30 days.',

    // Calculations
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',

    // PDF
    generatePDF: 'Generate PDF',
    generating: 'Generating...',

    // PDF Template
    pdfInvoiceTitle: 'INVOICE',
    pdfBillTo: 'Bill To',
    pdfQty: 'Qty',
    pdfTotalDue: 'Total Due',
    pdfThankYou: 'Thank you for your business!',
    pdfPaymentInstructions: 'Please make payment by the due date. For questions, contact us at info@company.com',
    pdfCompanyName: 'Your Company Name',
    pdfCompanyAddress: '123 Business Street',
    pdfCompanyPhone: 'Phone',
    pdfCompanyEmail: 'Email',

    // Voice Commands Help
    voiceCommandsHelp: 'Voice Commands Help',
    commandExamples: 'Painting command examples',
    addItemCommand: 'Add 500 square feet exterior painting at 3.50',
    addItemCommand2: 'Add 10 gallons premium paint at 45',
    addItemCommand3: 'Add 8 hours labor at 65',
    customerCommand: 'Customer is Central Tower Building',
    taxCommand: 'Set tax to 10',

    // Errors
    error: 'Error',
    required: 'Required',
    invalidNumber: 'Invalid number',

    // Landing Page
    landingTitlePrefix: 'Voice-Powered',
    landingTitleHighlight: 'Invoicing',
    landingSubtitle: 'Create professional invoices with just your voice. The future of billing is here.',
    launchApp: 'Launch App',
    
    // Features
    featureVoiceTitle: 'Voice-Powered',
    featureVoiceDesc: 'Speak naturally to create invoices instantly.',
    featureExtractionTitle: 'Smart Extraction',
    featureExtractionDesc: 'AI automatically detects items, prices, and dates.',
    featurePdfTitle: 'Instant PDF',
    featurePdfDesc: 'Generate professional PDFs with a single command.',
    featureMultiLangTitle: 'Multi-Language',
    featureMultiLangDesc: 'Support for English and Spanish out of the box.',
  },
};
